
export const metadata = {
    title: "Header page",
    description: "Generated by create next app",
};
export default function Header(){
    return (
        <div>
            <h1 className={'text-white text-center text-4xl p-10'}> welcome to the header</h1>
        </div>
    )
}
